// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2dP3Jv0CTpD4yAn1H71Bji2V4SuHlrI',
    appId: '1:132383153406:web:1df22bf61be9d9196799af',
    messagingSenderId: '132383153406',
    projectId: 'writles',
    authDomain: 'writles.firebaseapp.com',
    storageBucket: 'writles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAFTfylnd1zGoPwTpwa6jWD8ElYtZjWcc',
    appId: '1:132383153406:android:490aaa78a1299ecf6799af',
    messagingSenderId: '132383153406',
    projectId: 'writles',
    storageBucket: 'writles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsPQDWB9rKk8fyW5mI8Drf5890M40Z6ng',
    appId: '1:132383153406:ios:9a9280249e329a9d6799af',
    messagingSenderId: '132383153406',
    projectId: 'writles',
    storageBucket: 'writles.appspot.com',
    iosBundleId: 'com.example.writless',
  );
}
